"""initial schema

Revision ID: a8b9d63e11a2
Revises: 
Create Date: 2026-09-28 21:39:01.868703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b9d63e11a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('username_lower', sa.String(length=32), nullable=False),
    sa.Column('last_location', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username_lower')
    )
    op.create_table('verification_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_email'), ['email'], unique=False)

    op.create_table('location_shares',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('viewer_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'viewer_id')
    )
    with op.batch_alter_table('location_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_shares_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_shares_viewer_id'), ['viewer_id'], unique=False)

    op.create_table('parties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('join_code', sa.String(length=16), nullable=False),
    sa.Column('host_user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destination_name', sa.String(length=120), nullable=True),
    sa.Column('destination_address', sa.String(length=240), nullable=True),
    sa.Column('destination_latitude', sa.Float(), nullable=True),
    sa.Column('destination_longitude', sa.Float(), nullable=True),
    sa.Column('destination_start_time', sa.String(length=40), nullable=True),
    sa.Column('destination_source', sa.String(length=40), nullable=True),
    sa.Column('destination_source_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parties_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_host_user_id'), ['host_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_join_code'), ['join_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_parties_status'), ['status'], unique=False)

    op.create_table('party_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('party_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by_user_id', sa.String(), nullable=True),
    sa.Column('location_sharing_enabled', sa.Boolean(), nullable=False),
    sa.Column('check_in_status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['removed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id', 'user_id', name='uq_party_member_user')
    )
    with op.batch_alter_table('party_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_party_members_party_id'), ['party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_members_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_party_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_party_members_party_id'))

    op.drop_table('party_members')
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parties_status'))
        batch_op.drop_index(batch_op.f('ix_parties_join_code'))
        batch_op.drop_index(batch_op.f('ix_parties_host_user_id'))
        batch_op.drop_index(batch_op.f('ix_parties_expires_at'))

    op.drop_table('parties')
    with op.batch_alter_table('location_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_shares_viewer_id'))
        batch_op.drop_index(batch_op.f('ix_location_shares_owner_id'))

    op.drop_table('location_shares')
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_email'))

    op.drop_table('verification_codes')
    op.drop_table('users')
    # ### end Alembic commands ###
